### ISSUE TITLE
What lines need to change to make it as mp3 merger

### ISSUE THREAD

**Issue by bsde1234** [AbirHasan2005/VideoMerge-Bot#3]
in main.py, I changed 
if media.file_name.rsplit(".", 1)[-1].lower() not in [ "m4a", "mp3" ]:

Any more edits needed as a quick fix? please add here.

**Comment by AbirHasan2005** [comment]
Not so easy. Check [this](https://superuser.com/questions/314239/how-to-join-merge-many-mp3-files).
